/**
 * switch weak / auto-generated types
 * use `window.update_ids` to update
 */

/*
export type TAchievementID = string;
export type TConverterID = string;
export type TResourceID = string;
export type TActionID = string;
export type TRecordID = string;
// */

//*
// auto-generated
export type TAchievementID =
  | "pomodoro1"
  | "pomodoro2"
  | "pomodoro4"
  | "has_pomodoro4"
  | "idle_assets"
  | "cookie1"
  | "coal"
  | "iron"
  | "iron_ingot"
  | "iron_pickaxe"
  | "iron_pickaxe2"
  | "iron_pickaxe4"
  | "mana"
  | "mana100"
  | "three_grandma"
  | "no_mine"
  | "day2"
  | "steel"
  | "steel_pickaxe"
  | "steel_pickaxe2"
  | "steel_pickaxe4"
  | "cookie_volcano"
  | "burn_earth"
  | "sick"
  | "cookie_earth"
  | "science"
  | "green_mana"
  | "lumber"
  | "apple"
  | "grape"
  | "wine"
  | "forest"
  | "apple_tree"
  | "grape_tree"
  | "newton"
  | "day3"
  | "day5"
  | "day8"
  | "day13"
  | "day21"
  | "day34"
  | "day55"
  | "day89"
  | "day144"
  | "day233"
  | "pomodoro5"
  | "pomodoro9"
  | "pomodoro14"
  | "pomodoro23"
  | "pomodoro37"
  | "pomodoro60"
  | "pomodoro97"
  | "pomodoro157"
  | "pomodoro254"
  | "pomodoro411"
  | "pomodoro665"
  | "pomodoro1076"
  | "pomodoro1741"
  | "pomodoro2817"
  | "pomodoro4558"
  | "cookie3"
  | "cookie5"
  | "cookie8"
  | "cookie13"
  | "cookie21"
  | "cookie34"
  | "cookie55"
  | "cookie89"
  | "cookie144"
  | "cookie233"
  | "cookie377"
  | "cookie610"
  | "cookie987"
  | "cookie1597"
  | "cookie2584"
  | "steel3"
  | "steel5"
  | "steel8"
  | "steel13"
  | "steel21"
  | "steel34"
  | "steel55"
  | "steel89"
  | "steel144"
  | "steel233"
  | "steel377"
  | "steel610"
  | "steel987"
  | "steel1597"
  | "steel2584";
export type TConverterID =
  | "grandma"
  | "coal_mine"
  | "iron_mine"
  | "furnace"
  | "workbench"
  | "forest"
  | "apple_tree"
  | "newton"
  | "grape_tree";
export type TResourceID =
  | "pomodoro"
  | "cookie"
  | "coal"
  | "iron_ore"
  | "iron_ingot"
  | "iron_pickaxe"
  | "mana"
  | "steel"
  | "steel_pickaxe"
  | "green_mana"
  | "lumber"
  | "apple"
  | "science"
  | "grape"
  | "wine";
export type TActionID =
  | "click"
  | "burn_coal"
  | "no_hunger"
  | "create_forest"
  | "create_apple_tree"
  | "create_grape_tree"
  | "rain"
  | "breakData"
  | "soft_reset";
export type TRecordID =
  | "firstVisit"
  | "lastVisit"
  | "gotPomodoro"
  | "gotPomodoro_t1"
  | "lastPomodoro"
  | "days"
  | "manaLimit"
  | "totalAmountOfResources"
  | "totalAmountOfResources10"
  | "totalAmountOfResources20"
  | "totalAmountOfResources40"
  | "pollution"
  | "numSoftReset"
  | "numAchieved"
  | "used_mana";
// */
